### ISSUE TITLE
Problem in generated query: Rule 79

### ISSUE THREAD

**Issue by sandervd** [SEMICeu/adms-ap_validator#1]
The generated query adms-ap_validator/python-rule-generator/ADMS-AP Rules .txt
 contains, in rule 79, the following filter:
FILTER(!EXISTS {?o a }).

This filter is however invalid sparql syntax, and should probably be something like:
FILTER(!EXISTS {?o a spdx:checksumValue}).
This should be fixed in the source however, as as far as I understand, this file gets generated.

**Comment by EmidioStani** [comment]
Thanks @sandervd for reporting,

we will look into it.

**Comment by bertvannuffelen** [comment]
closed because of archiving repository
