### ISSUE TITLE
Valid file is not validating

### ISSUE THREAD

**Issue by claudiu-cristea** [SEMICeu/adms-ap_validator#2]
I'm loading the following RDF data into a graph, then I run the query from `adms-ap_validator/pages/adms-ap.txt` (with `@@@TOKEN-GRAPH@@@` replaced with my graph URL). This returns the following errors:
* rule 100: The mandatory class dcat:Dataset does not exist.
* rule 101: The mandatory class skos:Concept does not exist.
* rule 102: The mandatory class v:Kind does not exist.
* rule 103: The mandatory class foaf:Agent does not exist.

I've verified each line and apparently the whole content complies with ADMS v2. The validator disagrees with me. Could this be a bug or I'm missing something?

```xml
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:dct="http://purl.org/dc/terms/"
         xmlns:foaf="http://xmlns.com/foaf/0.1/"
         xmlns:v="http://www.w3.org/2006/vcard/ns#"
         xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:dcat="http://www.w3.org/ns/dcat#">
    <rdf:Description rdf:about="http://joinup.ec.europa.eu/unique_identifier">
        <rdf:type rdf:resource="dcat:Dataset"/>
        <dct:title xml:lang="en">Asset</dct:title>
        <dct:description xml:lang="en">This Asset...</dct:description>
        <dct:publisher rdf:resource="http://publisher"/>
        <dcat:contactPoint rdf:resource="http://contact"/>
        <dct:type rdf:resource="http://data.europa.eu/eira/PublicPolicy"/>
    </rdf:Description>

    <rdf:Description rdf:about="http://publisher">
        <rdf:type rdf:resource="foaf:Agent"/>
        <foaf:name>Some publisher</foaf:name>
    </rdf:Description>

    <rdf:Description rdf:about="http://contact">
        <rdf:type rdf:resource="v:Kind"/>
        <v:fn>Mr X</v:fn>
        <v:hasEmail>mrx@hexample.com</v:hasEmail>
    </rdf:Description>

</rdf:RDF>
```

**Comment by EmidioStani** [comment]
There is something weird in your validator.
I have loaded the ADMS rules in the DCAT-AP validator (http://dcat-ap.semic.eu/dcat-ap_validator.html) and inserting the RDF you specified and I don't have problems.

By the way the @@@TOKEN-GRAPH@@@ should be automatically filled by the validator which the identifier created and stored in your cookie

**Comment by claudiu-cristea** [comment]
EDIT: Deleted my initial comment. In that validation I forgot to add the rules

**Comment by EmidioStani** [comment]
@claudiu-cristea 
I was wrong.

I managed to replicate the error
<rdf:type rdf:resource="dcat:Dataset"/>

should be:

    <rdf:type rdf:resource="http://www.w3.org/ns/dcat#Dataset"/>

the same for the others (Catalog, etc.)

Definitely is something weird :-)

**Comment by claudiu-cristea** [comment]
@EmidioStani I understand now how to use http://dcat-ap.semic.eu/dcat-ap_validator.html but now I'm having other error: An invalid ADMS v2 data blob still passes. I tried the 2 scenarios, 1st is expected to validate, the 2nd to show errors -- but both are passing. I'm using  `http://www.w3.org/ns/dcat#Dataset` instead of `dcat:Dataset` in both cases:

**Case 1**

- Selected "Validate by Direct Input" tab
- Filled with data from this ticket in the "Direct input:" text area (`http://www.w3.org/ns/dcat#Dataset` instead of `dcat:Dataset`)
- Filled with contents of https://github.com/SEMICeu/adms-ap_validator/blob/master/pages/adms-ap.txt the "SPARQL query:" text area, under "More Options"
- Expected: pass validation
- Result: validation passed

**Case 2**

- Selected "Validate by Direct Input" tab
- Filled with data from this ticket in the "Direct input:" text area (`http://www.w3.org/ns/dcat#Dataset` instead of `dcat:Dataset`) but I removed the `<dct:publisher .../>` and `<dcat:contactPoint .../>` lines and also the entire referred objects. I did this to force  validation errors as the 2 properties are mandatory in ADMS v2:
     ```xml
     <?xml version="1.0" encoding="utf-8"?>
      <rdf:RDF xmlns:dct="http://purl.org/dc/terms/"
              xmlns:foaf="http://xmlns.com/foaf/0.1/"
              xmlns:v="http://www.w3.org/2006/vcard/ns#"
              xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
              xmlns:dcat="http://www.w3.org/ns/dcat#">
         <rdf:Description rdf:about="http://asset">
             <rdf:type rdf:resource="http://www.w3.org/ns/dcat#Dataset"/>
             <dct:title xml:lang="en">Asset</dct:title>
             <dct:description xml:lang="en">This Asset...</dct:description>
             <dct:type rdf:resource="http://data.europa.eu/eira/PublicPolicy"/>
         </rdf:Description>
     </rdf:RDF>
     ```
- Filled with contents of https://github.com/SEMICeu/adms-ap_validator/blob/master/pages/adms-ap.txt the "SPARQL query:" text area, under "More Options"
- Expected: fail validation
- Result: validation passed

EDIT: And also `http://www.w3.org/ns/dcat#Dataset` and `dcat:Dataset` are exactly the same. I wonder why that would be an invalid RDF resource.

**Comment by EmidioStani** [comment]
I tested with your example of case 2 and I get the (correctly) the errors (copied from clipboard) :

DCAT-AP Validator: SPARQL Query Result

Class Name	Rule ID	Rule Severity	Rule Description	Message	Subject	Predicate	Object
dcat:Dataset	1	error	dcat:contactPoint is a required property for dcat:Dataset.	The dcat:Dataset http://asset does not have a dcat:contactPoint property.	http://asset	http://www.w3.org/ns/dcat#contactPoint	
dcat:Dataset	5	error	dct:publisher is a required property for dcat:Dataset.	The dcat:Dataset http://asset does not have a dct:publisher property.	http://asset	http://purl.org/dc/terms/publisher	
skos:Concept	101	error	skos:Concept does not exist.	The mandatory class skos:Concept does not exist.			
v:Kind	102	error	v:Kind does not exist.	The mandatory class v:Kind does not exist.			
foaf:Agent	103	error	foaf:Agent does not exist.	The mandatory class foaf:Agent does not exist.			

Concerning:

> EDIT: And also http://www.w3.org/ns/dcat#Dataset and dcat:Dataset are exactly the same. I wonder why that would be an invalid RDF resource.

you are replacing a Qname with a URI, in RDF world that is an assumption that can be done but not in XML world, for example the localpart of a Qname cannot start with a number for example:
http://www.statutelaw.gov.uk/legislation/3032571
you cannot replace it with abc:3032571

I guess the internal XML parser internal to the triplestore doesn't allow Qname replacement, see: https://www.w3.org/TR/REC-xml-names/#ns-qualnames

**Comment by claudiu-cristea** [comment]
@EmidioStani I wonder why I'm getting other output. Are you manually replacing `@@@TOKEN-GRAPH@@@` with the graph from the cookie after pasting the rules from https://github.com/SEMICeu/adms-ap_validator/blob/master/pages/adms-ap.txt?

**Comment by EmidioStani** [comment]
Yes I replace it with token id that is generated automatically when I access in the validator

**Comment by claudiu-cristea** [comment]
@EmidioStani thank you for your patience. Finally I managed to validate data. The problem was that my sample data was not compliant. Here's the data, corrected to pass the validation:

```xml
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:dct="http://purl.org/dc/terms/"
         xmlns:foaf="http://xmlns.com/foaf/0.1/"
         xmlns:v="http://www.w3.org/2006/vcard/ns#"
         xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:dcat="http://www.w3.org/ns/dcat#"
         xmlns:skos="http://www.w3.org/2004/02/skos/core#">
    <rdf:Description rdf:about="http://asset">
        <rdf:type rdf:resource="http://www.w3.org/ns/dcat#Dataset"/>
        <dct:title>Asset</dct:title>
        <dct:description>This is an Asset.</dct:description>
        <dct:publisher rdf:resource="http://publisher"/>
        <dcat:contactPoint rdf:resource="http://contact"/>
        <dct:type rdf:resource="http://vocabulary/term"/>
    </rdf:Description>

    <rdf:Description rdf:about="http://publisher">
        <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Agent"/>
        <dct:type rdf:resource="http://purl.org/adms/publishertype/Company"/>
        <foaf:name>The Publisher</foaf:name>
    </rdf:Description>

    <rdf:Description rdf:about="http://contact">
        <rdf:type rdf:resource="http://www.w3.org/2006/vcard/ns#Kind"/>
        <v:fn>Contact</v:fn>
        <v:hasEmail rdf:datatype="v:Email">contact@hexample.com</v:hasEmail>
    </rdf:Description>

    <rdf:Description rdf:about="http://vocabulary/term">
        <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
        <skos:label>Term</skos:label>
        <skos:inScheme rdf:resource="http://vocabulary"/>
    </rdf:Description>

</rdf:RDF>
```

**Comment by claudiu-cristea** [comment]
@EmidioStani Probably the form can be improved to replace `@@@TOKEN-GRAPH@@@` with the cookie value also on form POST. This would cover the case when a user paste other rules set.
