### ISSUE TITLE
Wrong range type in rule 99

### ISSUE THREAD

**Issue by idimopoulos** [SEMICeu/adms-ap_validator#3]
I am leaving this here for future reference as it is wrong but according to specs, officially still correct.

I opened https://github.com/SEMICeu/ADMS-AP/issues/2 for this as it seems that there is an issue on the ADMS side. The issue is approved and is up to be fixed.

The problem with the rule 99 which is
```
skos:ConceptScheme;skos:hasTopConcept;0;0;LITERAL;;
```
is that the range is not actually LITERAL but an IRI.

As I said above, it needs first to be fixed upstream so for now it is according to definition, I will get back here when ADMS definition is updated.

**Comment by bertvannuffelen** [comment]
closed because of archiving repository
