### ISSUE TITLE
Rule 15: dct:language does not need a dct:LinguisticSystem

### ISSUE THREAD

**Issue by idimopoulos** [SEMICeu/adms-ap_validator#4]
We are using the adms validator to validate entities created in our project. For a collection, i.e. a dcat:Catalog, we have the dct:language property to point to one of the terms in the  MDR Languages (http://publications.europa.eu/mdr/resource/authority/language/skos/languages-skos.rdf).

The validator has the following, in rule 15:
```
WHERE {
     ?s a dcat:Dataset.
     ?s dct:language ?o.
     ?o ?p ?val.
     FILTER(!EXISTS {?o a dct:LinguisticSystem}).
```
which apparently requires that the referred language is an instance of the LinguisticSystem class.

Initially, I thought that the catalogue defined above is not a compliant catalogue since the values are instances of `skos:Concept` and that the catalogue was an invalid one. However, in [dcat documentation](https://www.w3.org/TR/vocab-dcat/#Property:catalog_language), it is stated, that for the `language` property, `Resources defined by the Library of Congress (1, 2) SHOULD be used.` where 1 and 2 are links pointing to http://id.loc.gov/vocabulary/iso639-1.html and http://id.loc.gov/vocabulary/iso639-2.html.

The thing is that the terms found in those pages are also instances of the `skos:Concept` class and not the `LinguisticSystem` class.

I also opened https://github.com/SEMICeu/ADMS-AP/issues/5 for clarification and got a reply, which confirmed my thoughts, that reference to a Concept can be valid as long as the referred class can be inferred as the class required by the `:range` property.

According to the above, probably the rule should be upgraded to also include Concept classes or simply request that the referred object is a class.

**Comment by bertvannuffelen** [comment]
closed because of archiving repository
