### ISSUE TITLE
Rule 41: dct:format and dct:mediaTypeOrExtent

### ISSUE THREAD

**Issue by idimopoulos** [SEMICeu/adms-ap_validator#5]
Recently I opened https://github.com/SEMICeu/adms-ap_validator/issues/4 which talks about how even if a value range targets a specific class and the value refers to an instance of another class (e.g. skos:Concept), it is acceptable if the referred class can be inferred as the range class.

Now, I cannot say for sure if this makes sense or not but according to the other issue, issued catalogues seem to behave that way. 
In this issue, another case emerges with the same pattern.
Rule 41, requires that the dct:format points to a class of type dct:mediaTypeOrExtent.

In our project, in which we are using the adms, we are using the European published catalogue of mime types which can be found at publications.europa.eu/mdr/resource/authority/file-type/skos-ap-eu/filetypes-skos-ap-act.rdf or publications.europa.eu/mdr/resource/authority/file-type/ where you can find it in multiple formats.

Terms of this catalogue are instances of the class skos:Concept instead of explicitly being of dcat:mediaTypeOrExtent.

Another example is http://dbpedia.org/data/Comma-separated_values which is another catalogue instance of a file type. This also seems to not be an instance of a mediaTypeOrExtent though I could not find the full catalogue definition for that.

So *IF* and only *IF* the above assumptions are correct, then probably the validator should not require the classes for these objects.

**Comment by bertvannuffelen** [comment]
closed because of archiving repository
