### ISSUE TITLE
Rules 13, 32 too strict

### ISSUE THREAD

**Issue by idimopoulos** [SEMICeu/adms-ap_validator#7]
According to the adms-ap generated query, rules 13 and 32 demand that the dcat:landingPage and the foaf:Page properties of the dcat:Dataset, must be of type foaf:Document.
Today we tried to validate a piece of information which did not validate with this.
The owner of the document had an asset distribution with IRI let's say http://example.com/asset_distribution.
The problem starts with having the page of the distribution, be the IRI itselft. That means that the landing page of the above IRI is itself.
While normally the validator could consider a URL as a foaf:Document, now the IRI has a type, and it is an asset distribution class.

This makes these validation rules a bit strict as normally, an IRI can be referenced by itself as a landing page as well.

As a reference, I would like to provide the http://xmlns.com/foaf/spec/#term_Document which contains information on the value type. As noted in the above link, the foaf:Document data type can only conflict with the foaf:Project and foaf:Organization classes.
That would probably make the query for rule 13 something like
```
# Rule_ID:13 dcat:Dataset - dcat:landingPage USAGE
  {SELECT DISTINCT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
   WHERE {
     ?s a dcat:Dataset.
     ?s dcat:landingPage ?o.
     ?o ?p ?val.
     {{ FILTER EXISTS {?o a foaf:Project} } UNION { FILTER EXISTS {?o a foaf:Organization} }}.
     BIND ('dcat:Dataset' AS ?Class_Name).
     BIND (13 AS ?Rule_ID).
     BIND ('error' AS ?Rule_Severity).
     BIND ('dcat:landingPage should be a foaf:Document.' AS ?Rule_Description).
     BIND (concat('dcat:Dataset ',str(?s),' does not have a dcat:landingPage property of type foaf:Document.') AS ?Message).
   }
  }
```
And rule 32 something like
```
# Rule_ID:32 dcat:Dataset - foaf:page USAGE
{SELECT DISTINCT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
   WHERE {
     ?s a dcat:Dataset.
     ?s foaf:page ?o.
     ?o ?p ?val.
     {{ FILTER EXISTS {?o a foaf:Project} } UNION { FILTER EXISTS {?o a foaf:Organization} }}.
     BIND ('dcat:Dataset' AS ?Class_Name).
     BIND (32 AS ?Rule_ID).
     BIND ('error' AS ?Rule_Severity).
     BIND ('foaf:page should be a foaf:Document.' AS ?Rule_Description).
     BIND (concat('dcat:Dataset ',str(?s),' does not have a foaf:page property of type foaf:Document.') AS ?Message).
   }
}
```
Since it is only the foaf:Project and foaf:Organization that cannot be considered as a document, then the Dataset itself can be considered one.

**Comment by bertvannuffelen** [comment]
closed because of archiving repository
